version: "3.8"

services:
  school_system_db:
    image: mysql:8
    container_name: school_system_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - school_system_data:/var/lib/mysql

  school_system_webapi:
    build: .
    container_name: school_system_webapi
    ports:
      - 8080:${SCHOOL_SYSTEM_PORT}
    depends_on:
      - school_system_db
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USERNAME: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

volumes:
  school_system_data:
